# Generated by Django 5.0.1 on 2026-01-18 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('COD', 'Cash on Delivery')], max_length=20, verbose_name='payment gateway')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='transaction ID')),
                ('gateway_order_id', models.CharField(blank=True, max_length=255, verbose_name='gateway order ID')),
                ('gateway_payment_id', models.CharField(blank=True, max_length=255, verbose_name='gateway payment ID')),
                ('gateway_signature', models.CharField(blank=True, max_length=255, verbose_name='gateway signature')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='payment method')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='card last 4 digits')),
                ('upi_id', models.CharField(blank=True, max_length=100, verbose_name='UPI ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='gateway response')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'), models.Index(fields=['order', 'status'], name='payments_order_i_3d4604_idx'), models.Index(fields=['gateway', 'status'], name='payments_gateway_3ac0c5_idx')],
            },
        ),
    ]
